image: node:8

before_script:
  - npm install

cache:
  paths:
    - node_modules/

# test:lint:
#  script:
#    - npm run lint

# test:vulnerabilities:
#  script:
#    - npm run vuln-test

test:node:8:
  script:
    - npm test
  coverage: '/^All files\s*\|\s*(\d+\.*\d+)\s*\|
# Matches 'Stmts', ex:
# File      |  % Stmts | % Branch |  % Funcs |  % Lines | Uncovered Line #s |
# ----------|----------|----------|----------|----------|-------------------| 
# All files |      100 |      100 |      100 |      100 |                   |

# test:node:7:
#  image: node:7
#  script:
#    - npm run build
#    - npm test

# Publish tagged versions to npm
# publish:
#  stage: deploy
#  only:
#    - tags
#    - triggers
#  script:
#    - npm run build
#    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
#    - npm publish