README_SRC:=$(SRC)/doc/README.md
README_BUILT:=README.md
DOC_EXTRACTOR:=$(SRC)/doc-extractor/doc-extractor.mjs

$(README_BUILT): $(README_SRC) $(DOC_EXTRACTOR) $(CATALYST_ALL_NON_TEST_JS_FILES_SRC)
	cp $< $@
	node $(DOC_EXTRACTOR)

BUILD_TARGETS:=$(README_BUILT)