# This file was generated by @liquid-labs/catalyst-builder-node. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-builder-node for further details

#####
# lint rules
#####

CATALYST_LINT_REPORT:=$(QA)/lint.txt
CATALYST_LINT_PASS_MARKER:=$(QA)/.lint.passed
LINT_TARGETS+=$(CATALYST_LINT_REPORT) $(CATALYST_LINT_PASS_MARKER)
PRECIOUS_TARGETS+=$(CATALYST_LINT_REPORT)

$(CATALYST_LINT_REPORT) $(CATALYST_LINT_PASS_MARKER): $(CATALYST_ALL_JS_FILES_SRC)
	mkdir -p $(dir $@)
	echo -n 'Test git rev: ' > $(CATALYST_LINT_REPORT)
	git rev-parse HEAD >> $(CATALYST_LINT_REPORT)
	( set -e; set -o pipefail; \
	  ESLINT_USE_FLAT_CONFIG=true $(CATALYST_ESLINT) \
	    --config $(CATALYST_ESLINT_CONFIG) \
	    . \
	    | tee -a $(CATALYST_LINT_REPORT); \
	  touch $(CATALYST_LINT_PASS_MARKER) )

lint-fix:
	@( set -e; set -o pipefail; \
	  ESLINT_USE_FLAT_CONFIG=true $(CATALYST_ESLINT) \
	    --config $(CATALYST_ESLINT_CONFIG) \
	    --fix . )

#####
# end lint
#####