# This file was generated by @liquid-labs/catalyst-lib-makefiles. Refer to
# https://npmjs.com/package/@liquid-labs/catalyst-lib-makefiles for further
# details

.PRECIOUS: $(PRECIOUS_TARGETS)

build: $(BUILD_TARGETS)
.PHONY+=build

all: build
.PHONY+=all

lint: $(LINT_TARGETS)
lint-fix: $(LINT_FIX_TARGETS)
.PHONY+=lint lint-fix

release: all qa package-lock.json
.PHONY+=release

test: $(TEST_TARGETS)
.PHONY+= test

qa: test lint
.PHONY+=qa
