name: Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build_and_test:
    name: Build and test package on ${{ matrix.os }}/${{ matrix.node-version }}

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node-version: [ 14.x, 16.x, 18.x, 20.x, 22.x ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        include:
          - os: macos-latest
            node-version: 14.x
            arch: x64

    steps:
      - uses: actions/checkout@v4
      - name: Node ${{ matrix.node_version }} - ${{ matrix.arch }} on ${{ matrix.os }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node_version }}
          architecture: ${{ matrix.arch }}
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
